spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
    port: 9091
  datasource:
    driverClassName: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost:${spring.h2.port}/mem:testdb;
    username: sa
    password:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

smart-contracts:
  block-chain-network-url: http://localhost:8545
  gas-limit: 1537000
  contract-address:
    mint-token: "0xfF40Dd766d24Fc3C92eb8FE38E1bdBccB3d55803"
    sale-token: "0xc359F46CEC82ac0586820Da70C122A4ab814b8f0"
  eoa:
    default-balance: 1
    system-private-key: "4d697d0ebc13dcaf5635748dd297b12e039655b91757761c221fc6b6509a2ae4"
    sample-private-key: "7728bd429a599fbb5024f492beeaf949f9f483ade4fb9a1a5c6c2b03cdccd2e0"
  wallet:
    upload-path: wallet

ipfs:
  prefix-url: http://localhost:8080/ipfs/%s
  address: /ip4/127.0.0.1/tcp/5001
  temp-upload-path: upload
