server:
  port: 8000
  shutdown: graceful

spring:
  application:
    name: smart-contract-service-app
  profiles:
    active: local

smart-contracts:
  initialize: false

logging:
  level:
    root: INFO
    org.web3j.protocol.http.HttpService: DEBUG
